# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0002_auto_20180325_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
